FLASK_APP = "app.py"
FLASK_SECRET_KEY = ""
FLASK_SQLALCHEMY_ECHO = 1
FLASK_RUN_PORT=8080
FLASK_JWT_SECRET_KEY=""
FLASK_SQLALCHEMY_TRACK_MODIFICATIONS = 0
FOOD_API_KEY=""
YOUTUBE_API_KEY=""  
GOOGLE_API_KEY= ""
GOOGLE_CSE_ID= ""
CLOUD_SQL_USERNAME=""
CLOUD_SQL_PASSWORD="!"
CLOUD_SQL_DATABASE=""
CLOUD_SQL_CONNECTION_NAME=""
DB_HOST="3"



