name: Build, Push, and Deploy to Cloud Run

on:
  push:
    branches: [ "main" ]

jobs:
  build_push_deploy:
    runs-on: ubuntu-latest

    steps:
      
      - uses: actions/checkout@v3

      
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./server
          file: ./server/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/recipesapp:latest

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy recipesapp-backend \
            --image docker.io/${{ secrets.DOCKERHUB_USERNAME }}/recipesapp:latest \
            --region us-central1 \
            --platform managed \
            --allow-unauthenticated \
            --quiet
