name: Deploy to Heroku

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Log in to Heroku Container Registry
      run: |
        echo "${{ secrets.HEROKU_API_KEY }}" | docker login --username=_ --password-stdin registry.heroku.com
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}

    - name: Build Docker image
      run: |
        docker build -t my-flask-backend .

    - name: Tag Docker image for Heroku
      run: |
        docker tag my-flask-backend registry.heroku.com/${{ secrets.HEROKU_APP_NAME }}/web

    - name: Push Docker image to Heroku
      run: |
        docker push registry.heroku.com/${{ secrets.HEROKU_APP_NAME }}/web

    - name: Release on Heroku
      run: |
        heroku container:release web --app ${{ secrets.HEROKU_APP_NAME }}
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        HEROKU_EMAIL: ${{ secrets.HEROKU_EMAIL }}
