name: Build, Push, and Deploy to Cloud Run

on:
  push:
    branches: [ "main" ]

jobs:
  build_push_deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Configure Docker to use Artifact Registry
      - name: Configure Docker to use Artifact Registry
        run: |
          echo "${{ secrets.GCP_SA_KEY }}" | docker login -u _json_key --password-stdin https://us-central1-docker.pkg.dev

      # Step 3: Build and push Docker image to Artifact Registry
      - name: Build and Push Docker Image
        run: |
          docker build -t us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/recipesapp-repo/recipesapp:latest ./server
          docker push us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/recipesapp-repo/recipesapp:latest

      # Step 4: Set up Google Cloud SDK
      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      # Step 5: Deploy to Cloud Run
      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy recipesapp-backend \
            --image us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/recipesapp-repo/recipesapp:latest \
            --region us-central1 \
            --platform managed \
            --allow-unauthenticated \
            --project ${{ secrets.GCP_PROJECT_ID }} \
            --quiet
